### PR TITLE
Minimal changes to work on 2017 and 2018 samples

### PR DESCRIPTION
**Pull request by wsicheng**
Some change in the python configurations:
- Removing CA15 jets
- Keep JetToolBox using for AK4chs and AK8puppi

Adding sample list for 2017 and 2018 samples:
In mc_ttbar_*.txt:
- The pt-binned amcnlo sample for w2lnu no longer exist, exchanged with ht-binned madgraph ones (njet-binned ones in commented state)
- Single top s-channel, changed from inclusive decay to lepton decay
- Diboson section, wz-2q2nu and zz-4q samples not found
- tZq-nunu doesn't exist for 2018
- ttbar-powheg-herwigpp samples aren't produced

In mc_qcd_*.txt:
- w2qq samples only exist in finer HT-binned ones, xsecs don't know, samples are in the commented out.
- qcd-flatp6 not found
- dy2qq not found in 2018, commented out
- ttbar-powheg exchanged with ttbar-amcatnlo

### CODE REVIEW

**Comment by hqucms** [comment]
@wsicheng Thank you very much for the changes!

Would you mind giving me edit permission to your branch (following https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can make a few changes on this PR?

**Comment by wsicheng** [comment]
@hqucms Sure of course, seems that the box is already checked.

**Comment by hqucms** [comment]
@wsicheng Thank you very much!

I fixed the workflow in `ak8_cff.py` and also updated the instructions in `README` for 2017 and 2018 samples.

**Comment by gouskos** [comment]
@wsicheng @hqucms  Thanks to both of you! Sicheng and myself can submit the jobs today. Sicheng please select either 2017 or 2018 [let me know which] and I take the other

**Pull request merged**
